services:
  watcher:
    build: ./watcher
    container_name: watcher
    user: "${PUID}:${PGID}"
    volumes:
      - ./shared/downloads:/downloads
      - ./shared/pipeline:/pipeline

  queue:
    build: ./queue
    container_name: queue
    user: "${PUID}:${PGID}"
    volumes:
      - ./shared/pipeline:/pipeline

  splitter:
    build: ./splitter
    container_name: splitter

  converter:
    build: ./converter
    container_name: converter

  combiner:
    build: ./combiner
    container_name: combiner

  metadata:
    build: ./metadata
    container_name: metadata

  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: "1000:1000"
    ports:
      - "4533:4533"
    restart: unless-stopped
    volumes:
      - ./navidrome/data:/data
      - ./shared/music:/music:ro

  deemix:
    image: registry.gitlab.com/bockiii/deemix-docker
    container_name: deemix
    volumes:
      - ./shared/downloads:/downloads
      - ./deemix/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - ARL=1234567  # Replace with your actual ARL cookie value
    ports:
      - "6595:6595"

  testing:
    build: ./testing
    container_name: testing

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # Main AMQP port
      - "15672:15672"   # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

volumes:
  rabbitmq_data:
