# version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  queue:
    image: nlivestudent/kip-queue:latest
    container_name: queue
    user: "${PUID}:${PGID}"
    volumes:
      - ./shared/pipeline:/pipeline
      - ./shared/originals:/originals
    depends_on:
      - rabbitmq
      - redis
    restart: unless-stopped

  watcher:
    image: nlivestudent/kip-watcher:latest
    container_name: watcher
    user: "${PUID}:${PGID}"
    volumes:
      - ./shared/downloads:/downloads
      - ./shared/pipeline:/pipeline
      - ./shared/originals:/originals
    depends_on:
      - rabbitmq
    restart: unless-stopped

  splitter:
    image: nlivestudent/kip-splitter:latest
    container_name: splitter
    environment:
      - SPLEETER_MODEL_PATH=/app/pretrained_models
    volumes:
      - ./shared/pipeline:/pipeline
      - ./shared/originals:/originals
      - ./shared/splitter_output:/splitter_output
      - ./shared/spleeter_models:/app/pretrained_models
    depends_on:
      - rabbitmq
    restart: unless-stopped

  converter:
    image: nlivestudent/kip-converter:latest
    container_name: converter
    volumes:
      - ./shared/splitter_output:/splitter_output
      - ./shared/converted_output:/converted_output
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    depends_on:
      - rabbitmq
    restart: unless-stopped

  combiner:
    image: nlivestudent/kip-combiner:latest
    container_name: combiner
    volumes:
      - ./shared/pipeline:/pipeline
      - ./shared/splitter_output:/splitter_output
      - ./shared/music:/music
    depends_on:
      - converter
      - rabbitmq
    restart: unless-stopped

  metadata:
    image: nlivestudent/kip-metadata:latest
    container_name: metadata
    volumes:
      - ./shared/music:/music
      - ./shared/pipeline:/pipeline
      - ./shared/converted_output:/converted_output
      - ./shared/splitter_output:/splitter_output
    depends_on:
      - rabbitmq
    restart: unless-stopped

  cleanup:
    image: nlivestudent/kip-cleanup:latest
    container_name: cleanup
    volumes:
      - ./shared/pipeline:/pipeline
      - ./shared/splitter_output:/splitter_output
      - ./shared/music:/music
      - ./shared/originals:/originals
    depends_on:
      - rabbitmq
    restart: unless-stopped

  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: "${PUID}:${PGID}"
    ports:
      - "4533:4533"
    volumes:
      - ./navidrome/data:/data
      - ./shared/music:/music:ro
    restart: unless-stopped

  deemix:
    image: registry.gitlab.com/bockiii/deemix-docker
    container_name: deemix
    volumes:
      - ./shared/downloads:/downloads
      - ./deemix/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - ARL=1234567
    ports:
      - "6595:6595"
    restart: unless-stopped

volumes:
  rabbitmq_data:
  redis_data:
